import type { Metadata, Viewport } from "next";
import Script from "next/script";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import { Providers } from "@/components/providers";
import { AppShell } from "@/components/shell/app-shell";
import "./globals.css";

const TITLE = "FreeTools · Privacy-first web utilities";
const DESCRIPTION =
  "60 free developer, design, media, and productivity tools that run entirely in your browser. Your files never leave your device.";

export const metadata: Metadata = {
  metadataBase: new URL("https://www.freetools.click"),
  title: {
    default: TITLE,
    template: "%s · FreeTools",
  },
  description: DESCRIPTION,
  applicationName: "FreeTools",
  openGraph: {
    title: TITLE,
    description: DESCRIPTION,
    url: "https://www.freetools.click/",
    siteName: "FreeTools",
    locale: "en_US",
    type: "website",
    // og:image is generated by app/opengraph-image.tsx (1200x630).
  },
  twitter: {
    card: "summary_large_image",
    title: TITLE,
    description: DESCRIPTION,
    // twitter:image is generated by app/twitter-image.tsx.
  },
};

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#fafafa" },
    { media: "(prefers-color-scheme: dark)", color: "#050505" },
  ],
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${GeistSans.variable} ${GeistMono.variable}`}
    >
      <body>
        <Providers>
          <AppShell>{children}</AppShell>
        </Providers>

        {/* Google tag (gtag.js) */}
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-7Y4M9GS4EB"
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-7Y4M9GS4EB');`}
        </Script>
      </body>
    </html>
  );
}
