import type { Metadata, Viewport } from "next";
import { Analytics } from "@vercel/analytics/next";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import { Providers } from "@/components/providers";
import { AppShell } from "@/components/shell/app-shell";
import "./globals.css";

const TITLE = "FreeTools · Privacy-first web utilities";
const DESCRIPTION =
  "60 free developer, design, media, and productivity tools that run entirely in your browser. Your files never leave your device.";

export const metadata: Metadata = {
  metadataBase: new URL("https://www.freetools.click"),
  title: {
    default: TITLE,
    template: "%s · FreeTools",
  },
  description: DESCRIPTION,
  applicationName: "FreeTools",
  openGraph: {
    title: TITLE,
    description: DESCRIPTION,
    url: "https://www.freetools.click/",
    siteName: "FreeTools",
    locale: "en_US",
    type: "website",
    // og:image is generated by app/opengraph-image.tsx (1200x630).
  },
  twitter: {
    card: "summary_large_image",
    title: TITLE,
    description: DESCRIPTION,
    // twitter:image is generated by app/twitter-image.tsx.
  },
};

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#fafafa" },
    { media: "(prefers-color-scheme: dark)", color: "#050505" },
  ],
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${GeistSans.variable} ${GeistMono.variable}`}
    >
      <body>
        <Providers>
          <AppShell>{children}</AppShell>
        </Providers>

        {/* Cookieless, privacy-friendly traffic stats. Sets no cookies and does
            not track visitors across sites — keeps our "no cookies" promise true. */}
        <Analytics />
      </body>
    </html>
  );
}
