import { ImageResponse } from "next/og";
import { getTool } from "@/lib/tools-registry";

/**
 * Shared builder for the per-tool Open Graph share image. Each
 * app/tools/<slug>/opengraph-image.tsx is a three-line file that calls
 * toolOgImage("<slug>") — those files are generated by scripts/gen-tool-og.mjs.
 *
 * Visual language mirrors the site-wide banner in app/opengraph-image.tsx:
 * #050505 canvas, gold radial glow, gold rounded-square wrench mark.
 *
 * Satori notes: every element with 2+ children needs display:"flex", all
 * styling is inline, and no external fonts are loaded (default sans only).
 */

export const OG_SIZE = { width: 1200, height: 630 } as const;
export const OG_CONTENT_TYPE = "image/png";

const WRENCH =
  "M14.7 6.3a1 1 0 0 0 0 1.4l1.6 1.6a1 1 0 0 0 1.4 0l3.77-3.77a6 6 0 0 1-7.94 7.94l-6.91 6.91a2.12 2.12 0 0 1-3-3l6.91-6.91a6 6 0 0 1 7.94-7.94l-3.76 3.76z";

/** Long names must never overflow: step the headline down as the name grows. */
function headlineSize(name: string): number {
  if (name.length <= 18) return 84;
  if (name.length <= 30) return 72;
  if (name.length <= 44) return 60;
  return 52;
}

export function toolOgImage(slug: string): ImageResponse {
  const tool = getTool(slug);

  // Fall back to generic FreeTools copy rather than throwing — a throw here
  // would fail the build for the whole route.
  const name = tool?.name ?? "FreeTools";
  const description =
    tool?.description ?? "Free, private, in-browser tools. Nothing ever leaves your device.";
  const category = tool?.category ?? "Free online tools";

  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          display: "flex",
          flexDirection: "column",
          justifyContent: "space-between",
          background: "#050505",
          backgroundImage:
            "radial-gradient(1000px 500px at 50% -10%, rgba(234,179,8,0.18), transparent 60%)",
          color: "#ffffff",
          fontFamily: "sans-serif",
          padding: "64px 72px",
        }}
      >
        {/* Header row: logo mark + wordmark */}
        <div style={{ display: "flex", alignItems: "center", gap: 24 }}>
          <div
            style={{
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              width: 96,
              height: 96,
              borderRadius: 22,
              background: "#eab308",
            }}
          >
            <svg
              width="56"
              height="56"
              viewBox="0 0 24 24"
              fill="none"
              stroke="#050505"
              strokeWidth={2}
              strokeLinecap="round"
              strokeLinejoin="round"
            >
              <path d={WRENCH} />
            </svg>
          </div>
          <div style={{ fontSize: 40, fontWeight: 700, letterSpacing: -1 }}>FreeTools</div>
        </div>

        {/* Body: category pill, tool name, description */}
        <div style={{ display: "flex", flexDirection: "column" }}>
          <div style={{ display: "flex" }}>
            <div
              style={{
                display: "flex",
                padding: "9px 22px",
                borderRadius: 999,
                border: "1px solid rgba(234,179,8,0.4)",
                color: "#eab308",
                fontSize: 24,
                fontWeight: 600,
              }}
            >
              {category}
            </div>
          </div>

          <div
            style={{
              fontSize: headlineSize(name),
              fontWeight: 800,
              letterSpacing: -2,
              lineHeight: 1.05,
              marginTop: 28,
            }}
          >
            {name}
          </div>

          <div
            style={{
              fontSize: 30,
              color: "#9ca3af",
              lineHeight: 1.35,
              marginTop: 22,
              maxWidth: 940,
            }}
          >
            {description}
          </div>
        </div>

        {/* Footer */}
        <div
          style={{
            display: "flex",
            alignItems: "center",
            gap: 18,
            fontSize: 24,
            color: "#6b7280",
          }}
        >
          <div style={{ color: "#eab308", fontWeight: 600 }}>freetools.click</div>
          <div>·</div>
          <div>Runs 100% in your browser — no uploads</div>
        </div>
      </div>
    ),
    { ...OG_SIZE },
  );
}
