import { toolOgImage, OG_SIZE, OG_CONTENT_TYPE } from "@/lib/og-tool-image";

// Auto-generated by scripts/gen-tool-og.mjs — safe to regenerate.
export const alt = "Base64 Encode / Decode — FreeTools";
export const size = OG_SIZE;
export const contentType = OG_CONTENT_TYPE;

export default function Image() {
  return toolOgImage("base64");
}
