import type { Metadata } from "next";
import { getTool } from "@/lib/tools-registry";
import { ToolPage } from "@/components/tool/tool-page";
import { ComingSoonTool } from "@/components/tool/coming-soon-tool";

// Auto-generated by scripts/gen-coming-soon.mjs — safe to regenerate.
const SLUG = "uuid-generator";
const tool = getTool(SLUG);

export const metadata: Metadata = {
  title: tool?.name ?? "FreeTools",
  description: tool ? `${tool.description} 100% in your browser — no uploads.` : undefined,
};

export default function Page() {
  return (
    <ToolPage slug={SLUG}>
      <ComingSoonTool slug={SLUG} />
    </ToolPage>
  );
}
