// @ts-check
/**
 * Generates a per-tool Open Graph image route for every tool in
 * lib/tools-registry.ts, so each /tools/<slug> page shares a banner with that
 * tool's own name + description instead of the site-wide banner.
 *
 * Each generated file is a thin wrapper around toolOgImage() in
 * lib/og-tool-image.tsx — all the design lives there, so re-running this script
 * is cheap and safe (idempotent: identical files are left untouched).
 *
 * Run:  node scripts/gen-tool-og.mjs
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const registryPath = join(root, "lib", "tools-registry.ts");
const toolsDir = join(root, "app", "tools");

// ── Parse every slug (and its name) out of the registry ────────────────
const src = readFileSync(registryPath, "utf8");
const slugRe = /slug:\s*"([^"]+)"/g;
/** @type {{ slug: string, name: string }[]} */
const tools = [];
let match;
while ((match = slugRe.exec(src)) !== null) {
  const slug = match[1];
  // Look at this tool object only, up to the next slug declaration.
  const nextSlug = src.indexOf("slug:", slugRe.lastIndex);
  const block = src.slice(slugRe.lastIndex, nextSlug === -1 ? undefined : nextSlug);
  const nameMatch = block.match(/name:\s*"([^"]+)"/);
  tools.push({ slug, name: nameMatch ? nameMatch[1] : slug });
}

const template = (
  /** @type {string} */ slug,
  /** @type {string} */ name,
) => `import { toolOgImage, OG_SIZE, OG_CONTENT_TYPE } from "@/lib/og-tool-image";

// Auto-generated by scripts/gen-tool-og.mjs — safe to regenerate.
export const alt = ${JSON.stringify(`${name} — FreeTools`)};
export const size = OG_SIZE;
export const contentType = OG_CONTENT_TYPE;

export default function Image() {
  return toolOgImage(${JSON.stringify(slug)});
}
`;

let written = 0;
let unchanged = 0;
for (const { slug, name } of tools) {
  const dir = join(toolsDir, slug);
  const file = join(dir, "opengraph-image.tsx");
  const next = template(slug, name);
  if (existsSync(file) && readFileSync(file, "utf8") === next) {
    unchanged++;
    continue;
  }
  mkdirSync(dir, { recursive: true });
  writeFileSync(file, next, "utf8");
  written++;
}

console.log(
  `\nWrote ${written} opengraph-image.tsx file(s), ${unchanged} already up to date ` +
    `(${tools.length} tools in the registry).`,
);
